import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api, ApiError } from "../api/client";
import { PasswordInput } from "../components/PasswordInput";
import { Alert } from "../components/Toast";
export function Signup() {
  const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(""); if (!/^\S+@\S+\.\S+$/.test(email)) return setError("Enter a valid email address."); if (password.length < 8) return setError("Use a password with at least 8 characters."); if (password !== confirm) return setError("Your passwords do not match."); setLoading(true); try { await api.signup(email, password); navigate(`/verify?email=${encodeURIComponent(email.trim().toLowerCase())}`, { state: { created: true } }); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to create your account."); } finally { setLoading(false); } };
  return <div className="card p-7 sm:p-9"><p className="text-sm font-semibold text-cyan-300">Get started</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Create your account</h1><p className="mt-2 text-sm text-slate-400">A few details and you’re ready to go.</p><form className="mt-8 space-y-5" onSubmit={submit} noValidate>{error && <Alert>{error}</Alert>}<div><label className="label" htmlFor="signup-email">Email address</label><input className="field" id="signup-email" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@company.com" required /></div><div><label className="label" htmlFor="signup-password">Password</label><PasswordInput id="signup-password" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 8 characters" required /><p className="mt-1.5 text-xs text-slate-500">Use 8–128 characters.</p></div><div><label className="label" htmlFor="confirm-password">Confirm password</label><PasswordInput id="confirm-password" autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Repeat your password" required /></div><button className="primary" disabled={loading}>{loading ? "Creating account…" : "Create account"}</button></form><p className="mt-7 text-center text-sm text-slate-400">Already have an account? <Link className="font-semibold text-cyan-300 hover:text-cyan-200" to="/login">Sign in</Link></p></div>;
}
